---
title: "Recorded Talks"
---

Ketamine and esketamine in suicide prevention. Breakthrough or hype? 9th Vilnius Conference on Suicide Intervention Methods. 22.11.2024. [Youtube](https://www.youtube.com/watch?v=CSbjF8aVGgA)

Suizid und Suizidprävention. Vortrag gehalten anläßlich des Welt-Suizidpräventionstages, organisiert von [MeinMed.at](https://www.meinmed.at/), 18.07.2023. [Link](https://www.facebook.com/meinmed.at/videos/in-diesem-informativen-webinar-wirst-du-von-dr-med-martin-pl%C3%B6derl-wichtige-infor/632660632352577/)

Sind Antidepressiva gute Medizin? Grams' Sprechstunde, 22.12.2022 (Interview mit Natalie Grams). <https://detektor.fm/wissen/grams-sprechstunde-antidepressiva>

Moon and suicide. An example of debunking a likely false positive finding. 2023 Workshop on Reproducibility, University of Toronto, 22.02.2023. [Youtube](https://www.youtube.com/watch?v=L3rjh6aH7xg)

Kann man sich auf die Evidenzbasierte Medizin verlassen? Beispiel Antidepressiva. Vortrag im Rahmen der "Sceptics in the Pub", GWUP Wien, 27.10.2022. [Youtube](https://www.youtube.com/watch?v=IZ9vyEv2Piw)

Suicide Risk Among LGBT+ individuals: Facts, Explanatory Models, and Prevention. 6th Vilnius Conference on Suicide Intervention Methods. 26.11.2021. [Youtube](https://www.youtube.com/watch?app=desktop&v=bV19PPKZctw)
