---
title: "CV"
---

I am currently affiliated with the following institutions:

-   Paracelsus Private Medical University, Salzburg, Austria [Link](http://www.pmu.ac.at/forschung/forschungsprogramme/suizidpraevention.html)

-   Center for Inpatient Psychotherapy and Crisis Intervention,
    University Clinic of Psychiatry and Psychotherapy, Christian - Doppler - Klinik, Salzburg, Austria [Link](https://salk.at/633.html)

-   Department of Clinical Psychology, Christian - Doppler - Klinik, Salzburg, Austria [Link](http://www.salk.at/160.html)

# CV

## Education

-   2014: Habilitation (Venia Docendi) at the Paracelsus Private Medical University

-   2006-2012: Psychotherapy (Gesellschaft für Logotherapie und Existenzanalyse, GLE); Licenced Psychotherapist since December 2012 

-   2003-2005: Curriculum Clinical Psychology and Health Psychology (BÖP); Licenced Clinical Psychologist and Health Psychologist since May 2005

-   2001-2004: Doctoral Study, Department of Psychology, University of Salzburg

-   1997-2001: Master Study, Department of Psychology, University of Salzburg

-   1986-1991; Technical College for Mechanical Engineering (HTL, Wels)

## Work

-   since 2015: Member of the Expert-Group for the development of Austrians Suicide Prevention Program (SUPRA)

-   since 2007: Gatekeeper-Trainings in Suicide Prevention (since 2016 certified SUPRA Trainer)

-   since 2005: Department for Crisis Intervention and Suicide Prevention (2005-2022), now transformed to Center for Inpatient Psychotherapy and Crisis Intervention, Christian Doppler Klinik, Paracelsus Medical University Salzburg

-   2004-2005: Assistant, Dept. of Psychology (Social Psychology), University of Salzburg

-   2000-2002: Research Assistant, SFB-012 (Logic & Cognitive Sciences), Univ. Salzburg

-   1998-2003: Nightshifts at the Caritas Homeless-Shelter in Salzburg

-   1991-1996: Technical Engineer (Sondermaschinenbau), Fa. Innotech (Linz) and Fa. SG-Automatisierungstechnik (Enns)

## Teaching

-   2003-2019 (and again starting 2026): University of Salzburg, Department of Psychology, Salzburg, Austria Lectures and seminars in social psychological research methods and suicide prevention

-   Since 2007: Paracelsus Private Medical University, Salzburg, Austria Lectures in psychological medicine (suicide prevention, placebo effects) and seminars about clinical research (questionnaires as tools)

-   2008 - 12017: University Curriculum Social Psychiatry / Crisis Managament, ProMente Upper Austria Weekend seminars in suicide prevention

-   since 2009: Fachhochschule Salzburg, University of Applied Sciences, Social Work, Austria: Lectures in suicide prevention, diversity management, psychopathology

## Peer Reviews

### Guest Reviewer

American Journal of Preventive Medicine, American Journal of Public Health, BMC Psychiatry, BMJ Open, BMC Psychiatry, BMC Public Health, British Journal of Psychiatry, Clinical Psychological Science, Crisis, Depression Research and Treatment, Epidemiology and Psychiatric Sciences, Expert Opinion Pharmacotherapy, Frontiers Psychiatry, Frontiers Psychology, Frontiers Psychiatry, International Review of Psychiatry, JAMA, Journal of Affective Disorders, Journal of Epidemiology and Community Health, Journal of Homosexuality, Journal of Lesbian Studies, Lancet Psychiatry, Molecular Psychiatry, Nordic Journal of Psychiatry, Pediatrics, PloS ONE, Psychiatric Research, Psychological Medicine, Psychotherapy and Psychosomatics, Sexual Medicine, Suicide and Life-Threatening Behavior, Social Psychiatry and Psychiatric Epidemiology, Stress and Health, Therapeutic Advances in Psychopharmacology. \

### Member of Review Board

Archives of Sexual Behavior (2011-2019), Existenzanalyse (2017-2020), Journal of the Gay and Lesbian Mental Health (since 2017-2019), Suizidprophylaxe (since 2010)

# Awards

-   First prize at the yearly agpro science award 2005

-   Poster Price at the Congress of the DGPPN 2008

-   Poster Prices at the Congress of the ÖGPPN 2009 and 2011

-   Scientific awards of the Paracelsus Medical University Salzburg\
    in bronze (2010, 2011, 2012, 2013), silver (2014, 2017), gold (2015, 2018), and platin (2019)
