<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Martin Plöderl – index</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Martin Plöderl</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../publications/index.html" rel="" target="">
 <span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../CV/index.html" rel="" target="">
 <span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../cycling/index.html" rel="" target="">
 <span class="menu-text">Cycling</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blogs/index.html" rel="" target="">
 <span class="menu-text">Blogs</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../recorded_talks/index.html" rel="" target="">
 <span class="menu-text">Recorded Talks</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">



<p><strong>Approving a drug for children and adolescents that is more likely to induce suicidality than relieve anxiety is concerning</strong></p>
<p><strong>Summary</strong></p>
<p>In this blog I review the approval of escitalopram for generalized anxiety disorder in children and adolescents and critically discuss the FDA approval document and the approval trial.<br>
In the approval trial, efficacy was not clinically meaningful, statistical significance was uncertain, and there were significantly more adverse events with escitalopram than with placebo. Compared to placebo, children and adolescents exposed to escitalopram were more likely to become suicidal than to experience improvement in anxiety. I also describe our experiences with trying to publish these critical arguments in psychiatric or medical journals. Overall, the approval is a case in point example of what can go wrong in evidence based psychiatry and evidence based medicine due to conflicts of interest and placing guild interest before patient safety.</p>
<p><strong>Background</strong></p>
<p>Based on my experience, most lay people and clinicians believe that a drug approved and endorsed by leading academics is safe, effective or even recommended. However, this is not generally the case, as demonstrated in the following review of the recent FDA approval of escitalopram for the treatment of generalized anxiety disorder (GAD) in children and adolescents.</p>
<p>A typical requirement for approval of a drug is that the drug must be superior to placebo in randomized clinical trials. In these trials, patients are randomly assigned to the drug or to placebo, ideally in a way so that neither patients nor study personnel know in which group patients were randomized (double blind design). Differences in the outcome between the drug group and placebo group can then be causally attributed as having been caused by the drug. This is why randomized controlled trials are considered the gold standard. Usually it takes two positive short term trials (where the drug outperforms the placebo group) and a longer term safety trial to approve a drug, for example by the Food and Drug Administration (FDA) or the European Medical Agency (EMA). Sometimes only one positive short-term drug trial is sufficient for approval, for example when there is a very promising new drug such as Esketamine for treatment resistant depression or when there is already existing evidence for the drug that should be approved for a new target group (e.g., children and adolescents) or different health problem (e.g., a subtype of depression). This also applied to the case I discuss here: escitalopram, a selective serotonin reuptake inhibitor (SSRI) which was already approved for the treatment of depression in adults before it was approved for pediatric GAD by the FDA <a href="https://www.zotero.org/google-docs/?uP2TB5">(Food and Drug Administration, 2023)</a>.</p>
<p>What many people and clinicians don’t know is that the requirement of a “positive” trial does not mean that the drug is superior to placebo in a clinically meaningful way. Instead, the drug only has to be “statistically significantly” superior to placebo. I will explain this later. Moreover, some drugs were approved despite there being more negative than positive trials. For example, the approval of esketamine for treatment resistant depression with only one positive and two negative short-term trials, or the SSRI sertraline with two positive trials (one in a strict sense) vs.&nbsp;three negative trials. Furthermore, both drugs were approved despite that the benefit was likely not clinically meaningful, at least according to common thresholds of clinical significance <a href="https://www.zotero.org/google-docs/?x7zYPU">(Hengartner &amp; Plöderl, 2022; Naudet et al., 2025)</a>.</p>
<p><strong>The efficacy of escitalopram is likely not clinically meaningful</strong></p>
<p>In the following I will summarize the results of a clinical trial that was essential for the approval of escitalopram for GAD in children and adolescents (referred to as “approval trial”) <a href="https://www.zotero.org/google-docs/?urAnzT">(Strawn et al., 2023)</a>. The trial was sponsored by Abb-Vie, the manufacturer of escitalopram under the trade name Lexapro. The first author of the trial publication was the prominent child/adolescent psychiatrist Jeffrey Strawn who disclosed financial relationships with Abb-Vie. In the trial, 275 children and adolescents diagnosed with GAD were randomized to receive either escitalopram or a placebo. The predefined primary outcome was improvement on the Pediatric Anxiety Rating Scale (PARS), a clinical interview where clinicians rate individual anxiety symptoms that are then summarized into a total score ranging from 0 to 25 points. At baseline, patients had an average score of about 18 points on the PARS. At the end of the 8-week treatment phase, patients treated with escitalopram showed an average improvement of 7.8 points, while patients treated with a placebo showed an average improvement of 6.4 points. The difference in improvement between the placebo and escitalopram groups was only -1.4 points. To account for the imprecision of estimates, a 95%-confidence interval (CI) was calculated. The 95% CI ranged from -2.7 to -0.2 points. If this 95% CI does not include zero, then the result is considered <em>statistically significant</em>. In this case, the result was statistically significant and consequently deemed “positive,” which was crucial for approval.</p>
<p>But what does a difference of -1.4 (95% CI -2.7 to -0.2) actually mean? This number may seem small at first glance, especially considering that values can range between 0 and 25. However, could this still be a clinically meaningful difference, one that young patients, their parents, and their clinicians would notice? Many readers may be surprised to learn that these questions are rather irrelevant for drug approval. Yet, they are absolutely crucial for patients and clinicians. To answer this question, we must consider the context of drug-placebo differences by examining the “clinical significance” or the “minimal clinically important difference (MCID).” While a detailed explanation of clinical significance and the MCID is beyond the scope of this text (refer to our review on the MCID for antidepressants <a href="https://www.zotero.org/google-docs/?FHUh2F">(Hengartner &amp; Plöderl, 2022)</a>), it is important to understand that estimating the MCID often involves exploring how changes in scores on a symptoms scale (like the PARS) align with the perceptions of clinicians or patients. This allows us to determine how many points of improvement on the PARS are needed for clinicians (or patients) to perceive at least a “minimal improvement.” A recent study indicated that the MCID for the PARS is ≥ 4 points <a href="https://www.zotero.org/google-docs/?cqctfU">(Cervin et al., 2025)</a>, which is higher than the drug-placebo difference observed in the approval trial of only -1.4 points (95% CI -2.7 to -0.2). <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>In contradiction to what I just concluded, both the authors of the approval trial <a href="https://www.zotero.org/google-docs/?h66TEk">(Strawn &amp; Mills, 2024)</a> and the FDA <a href="https://www.zotero.org/google-docs/?Gaakzh">(Food and Drug Administration, 2023)</a> concluded that efficacy of escitalopram is “clinically meaningful (FDA, p.&nbsp;13) without giving any scientific justification how they came to this conclusion. According to common criteria for the MCID, the correct conclusion is that the drug-placebo difference on the primary outcome (the PARS) was statistically significant but not clinically meaningful.</p>
<p>Moreover, a matter of concern is that even statistical significance in the approval trial was not robustly established in different analyses. Some patients dropped out of the trial and there are different statistical approaches to deal with missing data due to dropouts. Because there is no foolproof method, additional “sensitivity analyses” were conducted with different statistical approaches to see if the results are robust to the choice of the method. It turned out that statistical significance was lost in the “more informative” sensitivity analyses (Table 7 in the FDA report). Moreover, the FDA noted a change in the pre-specified data-analysis method in the sensitivity analysis - which is a problematic research practice: “the applicant’s post hoc sensitivity analysis does not ensure that the relationships between efficacy outcome and other factors are treated in a consistent way between the imputation model and the analysis model”. In the publication of the approval trial, neither this post-hoc change nor the results for the sensitivity analyses were mentioned <a href="https://www.zotero.org/google-docs/?RKCLBy">(Strawn et al., 2023)</a>. The fact that statistical significance was not robust should lead to the conclusion that there is uncertainty if the trial can be considered “positive” and, consequently, that the basic requirement for approval is not clearly met. Unfortunately, this did not alter the conclusions by the FDA.</p>
<p>Furthermore, this already sobering finding for the PARS as the primary outcome needs to be seen in light of the six secondary outcomes, which are summarized in Table 1. It turned out that escitalopram was not superior to placebo in any of these outcomes. For example, the fraction of patients who remitted in the trial, meaning that anxiety scores reduced into the normal range, was 17.7% in the escitalopram group and 18.8% with placebo. Not only did all secondary outcomes fail to be statistically significant, but the numerical results also show that all drug-placebo differences were close to zero.</p>
<p>For a correct interpretation of the results it is also important to acknowledge that such clinical trials overestimate efficacy because of methodological biases <a href="https://www.zotero.org/google-docs/?WwlN6e">(Hengartner, 2021; Hengartner &amp; Plöderl, 2018)</a>. For example, the approval trial was sponsored by the manufacturer of escitalopram and trials done by the manufacturer usually lead to larger efficacy compared to trials done by competing companies. We have shown this recently for fluoxetine for the treatment of pediatric depression <a href="https://www.zotero.org/google-docs/?hIytFB">(Plöderl, Lyus, et al., 2026)</a>. Efficacy is also overestimated because these trials are not perfectly blinded; that is, patients and clinicians can often guess correctly in which groups patients were assigned, and this is associated with overestimations of efficacy <a href="https://www.zotero.org/google-docs/?9XIaTl">(Hengartner &amp; Plöderl, 2018)</a>.</p>
<p>Overall, the findings on efficacy are weak and clearly contradict the conclusion that the benefit of escitalopram is clinically meaningful. It is important to note that the FDA approved escitalopram for pediatric GAD not only based on the approval trial but also on the assumption that its efficacy was already established in pediatric depression and adult GAD. However, these assumptions are solely based on “positive” trials without considering clinical significance. The efficacy of escitalopram for pediatric depression was only M = -2.6 (CI -5.3 to 0.0) points on the Childhood Depression Rating Scale which ranges from 17 to 113 and has an assumed MCID of 5 points <a href="https://www.zotero.org/google-docs/?iwR6zL">(Hetrick et al., 2021)</a>. Studies on escitalopram for adult GAD found a difference of -2.5 (CI -3.3 to -1.6) points on the Hamilton Anxiety Rating Scale which ranges from 0 to 56 points <a href="https://www.zotero.org/google-docs/?SsumtP">(Slee et al., 2019)</a>. While estimates of the MCID are unavailable, a 2.5 point change corresponds to only 4% of the scale range, which is not clinically relevant, as in other fields the MCID ranged between 12 and 18% of clinician rating scales <a href="https://www.zotero.org/google-docs/?FlFCWv">(Barrett et al., 2005)</a>. Overall, the benefit of escitalopram for the treatment of GAD in adults and depression in children and adolescents can not be considered clinically meaningful.</p>
<p>Table 1. <em>Outcomes in the approval trial</em></p>
<table class="table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Outcome</th>
<th style="text-align: left;">Placebo</th>
<th style="text-align: left;">Escitalopram</th>
<th style="text-align: left;">Mean difference (M), standardized mean difference (SMD), or odds ratio (OR), with the 95-% confidence interval in brackets</th>
<th style="text-align: left;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Primary: Pediatric Anxiety Rating Scale (PARS)</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">MD = -1.4 (-2.7 to -0.2) SMD = -0.3 (-0.5 to -0.0)*</td>
<td style="text-align: left;">0.03 0.05a 0.07b</td>
</tr>
<tr class="even">
<td style="text-align: left;">Children’s Global Assessment Scale (CGAS, range 1 to 100)c</td>
<td style="text-align: left;">15.70 (1.17)</td>
<td style="text-align: left;">17.43 (1.16)</td>
<td style="text-align: left;">MD = 0.73 (-1.46 to 4.93)</td>
<td style="text-align: left;">0.29</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Clinical Global Impression of Severity (CGI-S, range 1 to 7)c</td>
<td style="text-align: left;">-1.21 (0.10)</td>
<td style="text-align: left;">-1.34 (0.10)</td>
<td style="text-align: left;">MD = -0.13 (-0.39 to 0.13)</td>
<td style="text-align: left;">0.33</td>
</tr>
<tr class="even">
<td style="text-align: left;">PARS response in %c</td>
<td style="text-align: left;">33.3</td>
<td style="text-align: left;">39.5</td>
<td style="text-align: left;">OR = 1.25 (0.70 to 2.26)</td>
<td style="text-align: left;">0.45</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PARS remission in %c</td>
<td style="text-align: left;">18.8</td>
<td style="text-align: left;">17.7</td>
<td style="text-align: left;">OR = 1.16 (0.56 to 2.39)</td>
<td style="text-align: left;">0.70</td>
</tr>
<tr class="even">
<td style="text-align: left;">CGAS remission in %c</td>
<td style="text-align: left;">36.4</td>
<td style="text-align: left;">38.7</td>
<td style="text-align: left;">OR = 1.10 (0.59 to 2.03)</td>
<td style="text-align: left;">0.77</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CGI-S remission in %c</td>
<td style="text-align: left;">22.0</td>
<td style="text-align: left;">21.0</td>
<td style="text-align: left;">OR = 1.15 (0.51 to 2.57)</td>
<td style="text-align: left;">0.74</td>
</tr>
<tr class="even">
<td style="text-align: left;">Not reported in paper</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Suicide ideation during trial in %*</td>
<td style="text-align: left;">1.5</td>
<td style="text-align: left;">9.5</td>
<td style="text-align: left;">OR = 6.7 (1.8 to 47.2)</td>
<td style="text-align: left;">&lt;0.05</td>
</tr>
<tr class="even">
<td style="text-align: left;">Suicide ideation first occuring in trial in %*</td>
<td style="text-align: left;">0.7</td>
<td style="text-align: left;">5.1</td>
<td style="text-align: left;">OR = 6.6 (1.1 to 168.7)</td>
<td style="text-align: left;">&lt;0.05</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Adverse events other than suicide ideation in %*</td>
<td style="text-align: left;">37.5</td>
<td style="text-align: left;">55.5</td>
<td style="text-align: left;">OR = 2.1 (1.3 to 3.4)</td>
<td style="text-align: left;">&lt;0.01</td>
</tr>
</tbody>
</table>
<p>*Our calculation.<br>
a,b Results from the pre-specified sensitivity analysis not reported by Strawn et al.&nbsp;but by the FDA with a) results from the analysis with the last observation carry forward method and b) with pattern mixture modelling to replace missing data.<br>
c Secondary outcomes.</p>
<p><strong>Considerable harms</strong></p>
<p>Some may argue that the poor efficacy is not a problem as long as patients receive some form of treatment that does not cause harm. However, this is not the case here.</p>
<p>One side effect known to be problematic with selective serotonin reuptake inhibitors (SSRI) is suicidality, which is why SSRIs have a black box warning. The approval trial confirms this black box warning.</p>
<p>Although the authors of the approval trial and the FDA considered treatment emergent suicidality to be rare, in reality 9.5% of patients on escitalopram experienced suicidal thoughts compared to only 1.5% on placebo. This is about 7 times more suicidal ideation with escitalopram than with placebo and the difference is statistically significant (OR = 6.7, CI 1.8 – 47.2). Nearly a 10% occurrence is clearly not “rare.”</p>
<p>It is concerning that this significant finding was not discussed at all by the authors of the approval trial <a href="https://www.zotero.org/google-docs/?61xHjH">(Strawn et al., 2023)</a> and that it passed through the peer-review system of the journal. We pointed this out in a letter to the journal <a href="https://www.zotero.org/google-docs/?80THXv">(Plöderl et al., 2023)</a>. In response, the authors tried to downplay the disturbing findings, attributing them to imbalances in suicidality among the participating children and adolescents before the study <a href="https://www.zotero.org/google-docs/?Qp270j">(Strawn &amp; Mills, 2024)</a>. Their argument was that more patients who had previously experienced suicidal thoughts at any time in their life before the study were randomized to escitalopram than placebo (16% escitalopram, 12% placebo), so it is not surprising that more patients in the escitalopram group reported suicide ideation. Strawn et al.&nbsp;could have provided a statistical analysis controlling for the baseline difference, but they did not do this. Moreover, the authors ignored that the approximately 6-fold elevated rate of suicidality was also significant when only considering the first emergence of suicidality during the trial, that is, when excluding those with lifetime suicidality before the trial (5.1% vs.&nbsp;0.7%, OR = 6.6, CI 1.1-168.7). Numerically increased rates of suicidality were also found in a previous small study from the authors <a href="https://www.zotero.org/google-docs/?c60DYN">(Strawn et al., 2020)</a>. An increased risk for suicide ideation/behavior with SSRIs in general was also reported in trials for major depression in children, adolescents, and young adults <a href="https://www.zotero.org/google-docs/?ka92Fz">(Hetrick et al., 2021; Stone et al., 2009)</a>. Therefore, this signal for treatment emergent suicidality should not be considered a chance-finding but fits the body of evidence.</p>
<p>In addition to treatment emergent suicide ideation as a side effect of escitalopram, adverse events other than suicidality were clearly more common for patients on escitalopram versus placebo: 55.5% vs.&nbsp;37.5%, respectively, OR = 2.1, CI 1.3 – 3.4, p &lt; 0.01. It is important to note that the assessment of adverse events did not include sexual dysfunctions, which can occur in up to 80% of patients on SSRIs compared to 12% with placebo <a href="https://www.zotero.org/google-docs/?RSJSRa">(Serretti &amp; Chiesa, 2009)</a>. Therefore, the reported difference in adverse events is likely an underestimation. Additionally, there is evidence that sexual dysfunction can persist after stopping the drugs in some patients <a href="https://www.zotero.org/google-docs/?0HOPFt">(Healy &amp; Mangin, 2024; Pirani et al., 2024</a>). While this may be rare, for a drug with little to no efficacy, even rare severe events must be taken seriously.</p>
<p>Similar to the way benefits are often exaggerated, clinical trials are often biased in a way that adverse events are underreported or misclassified in favor of the drug. This bias has been demonstrated in independent analyses of pediatric antidepressant trials <a href="https://www.zotero.org/google-docs/?lsPNuz">(Aboustate et al., 2025; Gøtzsche &amp; Healy, 2022; Högberg et al., 2015; Le Noury et al., 2015)</a> and in clinical trials in general <a href="https://www.zotero.org/google-docs/?W3u750">(Golder et al., 2016)</a>. Therefore, it is reasonable to assume that the reported differences in harms between the drug and placebo are likely underestimated to some extent.</p>
<p><strong>Ignorance and rejection</strong></p>
<p>One would assume that our demonstration of the discrepancy between conclusions by the authors of the approval trial and the FDA (safe and effective) and the actual evidence (more harm than benefit) has substance, is highly clinically relevant, and therefore of interest to academic psychiatry and evidence based medicine.</p>
<p>Indeed, when I became aware of this trial, before approval by the FDA, I shared my concerns on X and this was one of my most widely shared threads. It seemed that even those who are critical of critics such as me acknowledged the problem and expressed concern. I then invited several esteemed researchers to summarize the concerns in a concise, scientific way. This included Joanna Moncrieff and Marc Horowitz, who both published extensively on the field of antidepressants, Florian Naudet who published on the efficacy of antidepressants and is an expert in meta-research and research integrity, and John Warren, who formerly worked for the UK Medicines Healthcare products Regulatory Agency (MHRA) as an Expert Medical Assessor evaluating new drug applications for the UK and Europe. The short commentary is available as a preprint <a href="https://www.zotero.org/google-docs/?k4TqK7">(Plöderl, Horowitz, et al., 2026)</a>.</p>
<p>When we attempted to publish our critical viewpoint in scientific journals, we encountered barriers. It took us nearly two years to finally have our arguments published as an opinion essay in “The Journal of Risk and Safety in Medicine”, which has a low impact factor but a reputation for being willing to publish inconvenient results.</p>
<p>Our short commentary was rejected without peer review by Lancet, Lancet Psychiatry, and BMJ-Evidence Based Medicine. We received no response when we tried to publish it as a blog there. A longer piece that I wrote as the sole author was rejected by the “Journal of Child Psychology and Psychiatry” and, after peer review, by “European Child &amp; Adolescent Psychiatry.” However, it is available as a preprint <a href="https://www.zotero.org/google-docs/?ze8jve">(Plöderl, 2025)</a>. Despite the urgency of getting our concerns published, it is not allowed to submit to different journals simultaneously, and the peer-review process could take weeks to months, resulting in almost 2 years passing. Rejections were typically accompanied by standard responses, citing too many submissions, lack of priority, or suggesting submitting to a different journal. While I understand this is automated, it is still disheartening to read such responses for a submission that could potentially prevent young anxious patients from becoming suicidal due to an approved drug treatment.</p>
<p>Unfortunately, this is not an isolated incident but rather typical when trying to publish inconvenient results. To increase the chances of critical publication, I learned that it is crucial to tone down as much as possible, showing extra humility to avoid upsetting editors and reviewers. Additionally, methodological limitations must be emphasized, and conclusions must be weakened to avoid challenging established treatments. This is in my experience starkly different from publishing papers that report convenient results. These papers not only have a much higher chance of being published, but also have more room to exaggerate the results, interpret effects causally when this is not possible, or even pass peer review despite obvious errors and trustworthiness issues (see my many <a href="https://ploederlm.github.io/publications/">letters</a> to the editor and postings on <a href="https://pubpeer.com/search?q=Martin+Pl%C3%B6derl">PubPeer</a>). Even when critical papers finally make it into peer review, reviewers tend to cherry pick evidence to dismiss critical arguments, or argue that some patients may benefit extraordinarily despite poor average efficacy, or simply dismiss randomized clinical trials and argue that efficacy is obvious from experience in clinical practice (see for example, the discussion section in one of our recent papers <a href="https://www.zotero.org/google-docs/?CbvLPq">(Plöderl, Lyus, et al., 2026)</a>).</p>
<p>Responses from leading psychiatrists to my/our critical work are sometimes harsh and go far beyond academic discussion. For example, when I challenged the outdated belief that <a href="https://cepuk.org/2021/06/16/guest-blog-really-depressed-people-need-antidepressants-do-they/">antidepressants work for severe depression</a> or when I argued that the <a href="https://ploederlm.github.io/blogs/Perlis_response/">average harm/benefit ratio for antidepressants is problematic</a>. Responses include saying that these are just opinions, that as a psychologist I am not in a position to talk about psychopharmacology, or that I have conflicting interests as a psychologist. I even have been contacted backchannel with accusations that I must have poor training and been told to be “humble in your statements. This is not a theoretical battle between you and guideline makers. Real patient lives are at stake.” (I agree with the latter sentence). In a scientific talk, leading psychiatrists from the UK compared our research on antidepressants with conspiracy theories, anti-elite movements, climate change denial, post truth ideologies, and Trumpism (see my response <a href="https://ploederlm.github.io/blogs/Response-Lewis/">here</a>). In an article in a scientific journal that went through peer-review, we were accused of pseudoscience, self-deception, social activism disguised as science, and opinion-based propaganda etc by an academic psychiatrist. To repeat, these accusations came from prominent figures in the field of psychiatry.</p>
<p>It seems that publishing critical information about antidepressants has become even more difficult since Trump became US-president and Kennedy started the “Make America Healthy Again” (MAHA) project, which is critical of psychopharmacological treatments for children and adolescents. In response to Trump’s fascist and anti-science politics, mainstream psychiatry’s biased reasoning is becoming more evident. A recent example comes from Jeffrey Strawn (the first author of the approval trial) and John Walkup, defending antidepressant use in children and adolescents <a href="https://www.zotero.org/google-docs/?VLbu1B">(Strawn &amp; Walkup, 2025)</a>. Their paper was published in a scientific journal and peer reviewed, but it is substantially in conflict with the evidence and MAHA could use this paper as a case-in-point example of motivated reasoning (see my debunking <a href="https://ploederlm.github.io/blogs/MAHA-responses/">here</a>). For example, Strawn and Walkup accused MAHA of fear mongering when pointing out the harms of antidepressants, but they do the same when they say that not offering antidepressant treatment increases suicides. It seems that a large part of academic psychiatry is more interested in keeping the status quo instead of taking well-founded criticism seriously. I am aware that this behavior is not unique to psychiatry but to any system that faces criticism, but this is no excuse and change is needed to not further erode trust in evidence based medicine.</p>
<p><em>Conclusion</em></p>
<p>The following conclusions are adapted from our opinion piece <a href="https://www.zotero.org/google-docs/?FyYJDq">(Plöderl, Horowitz, et al., 2026)</a>. The FDA concluded that the approval of escitalopram for the treatment of GAD in children and adolescents is justified because “the benefits of the product outweigh the risks.” <a href="https://www.zotero.org/google-docs/?KoXlks">(Food and Drug Administration, 2023, p.&nbsp;14).</a> However, as outlined above, this is in conflict with the actual findings of the approval trial. In this trial, estimated efficacy of escitalopram cannot be considered clinically meaningful, statistical significance for the primary outcome was uncertain (as shown in the sensitivity analyses), and escitalopram failed in all six secondary outcomes. In addition, there were significantly more adverse events with escitalopram than with placebo. Children and adolescents exposed to escitalopram were six to seven times more likely to develop suicide ideation during treatment with escitalopram than those exposed to placebo (OR = 6.7, CI 1.8 – 47.2). In fact, relative to placebo, children and adolescents exposed to escitalopram were more likely to develop suicidal ideation (9.5% vs.&nbsp;1.5%) or to experience any adverse event (55.5% vs.&nbsp;37.5%) than to experience response (improvement of ≥ 50%) in anxiety symptoms (39.5% vs.&nbsp;33.3%). This is in striking contrast to the conclusions by the FDA and the authors of the approval trial.</p>
<p>Overall, the harm/benefit ratio seems problematic for escitalopram for pediatric GAD and the findings for suicidality support the FDA’s black box warning. A common response to an overall negative harm/benefit ratio for the entire study population is arguing that a subset of patients may experience significant net benefit from the medication. However, as we have discussed elsewhere <a href="https://www.zotero.org/google-docs/?RC5Zpm">(Plöderl, Lyus, et al., 2026)</a>, there is no robust evidence for this claim, nor for identifying predictors of a good response (relative to placebo) and this does not change the conclusion that the majority of patients experience net harm. The inclusion of a ‘boxed warning’ about suicidality may be insufficient to substantially modify the risk of suicidality. If approval is maintained guideline committees and clinicians need to provide patients and families with honest information about the lack of evidence for clinically meaningful benefit, the evidence of harms, alternative approaches, and, if medication is used, close monitoring is required. Unfortunately, this is lacking for the majority of patients <a href="https://www.zotero.org/google-docs/?Cu8z9n">(Hansen et al., 2024)</a>.</p>
<p>In conclusion, the FDA should re-consider the approval decision, given the evidence suggests escitalopram is more likely to make this vulnerable population of anxious children and adolescents suicidal than to achieve response in anxiety symptoms.</p>
<p><strong>References</strong></p>
<p><a href="https://www.zotero.org/google-docs/?FqHu66">Aboustate, N., Jureidini, J., Woodman, R., Le Noury, J., Klau, J., Abi-Jaoude, E., &amp; Raven, M. (2025). Restoring TADS: RIAT reanalysis of the Treatment for Adolescents with Depression Study. <em>International Journal of Risk &amp; Safety in Medicine</em>, <em>36</em>(4), 218–237. https://doi.org/10.1177/09246479251337879</a><br>
<a href="https://www.zotero.org/google-docs/?FqHu66">Barrett, B., Brown, D., Mundt, M., &amp; Brown, R. (2005). Sufficiently Important Difference: Expanding the Framework of Clinical Significance. <em>Medical Decision Making</em>, <em>25</em>(3), 250–261. https://doi.org/10.1177/0272989X05276863</a><br>
<a href="https://www.zotero.org/google-docs/?FqHu66">Cervin, M., Kendall, P. C., Piacentini, J. C., Gosch, E. A., Wood, J. J., Schneider, S. C., Salloum, A., Birmaher, B., Guzick, A. G., Mataix-Cols, D., &amp; Storch, E. A. (2025). Assessing reliable change, MCID, treatment response, and remission using the Pediatric Anxiety Rating Scale (PARS) in youth with anxiety disorders. <em>Journal of Anxiety Disorders</em>, <em>115</em>, 103070. https://doi.org/10.1016/j.janxdis.2025.103070</a><br>
<a href="https://www.zotero.org/google-docs/?FqHu66">Food and Drug Administration. (2023, December 5). <em>Multi-disciplinary Review and Evaluation LEXAPRO (escitalopram) tablets / oral solution</em>. https://www.fda.gov/media/170239/download?attachment</a><br>
<a href="https://www.zotero.org/google-docs/?FqHu66">Golder, S., Loke, Y. K., Wright, K., &amp; Norman, G. (2016). Reporting of Adverse Events in Published and Unpublished Studies of Health Care Interventions: A Systematic Review. <em>PLOS Medicine</em>, <em>13</em>(9), e1002127. https://doi.org/10.1371/journal.pmed.1002127</a><br>
<a href="https://www.zotero.org/google-docs/?FqHu66">Gøtzsche, P. C., &amp; Healy, D. (2022). Restoring the two pivotal fluoxetine trials in children and adolescents with depression. <em>International Journal of Risk &amp; Safety in Medicine</em>, <em>33</em>(4), 385–408. https://doi.org/10.3233/JRS-210034</a><br>
<a href="https://www.zotero.org/google-docs/?FqHu66">Hansen, A. B., Hetlevik, Ø., Baste, V., Haukenes, I., Smith-Sivertsen, T., &amp; Ruths, S. (2024). Variation in general practitioners’ follow-up of depressed patients starting antidepressant medication: A register-based cohort study. <em>Family Practice</em>, cmae063. https://doi.org/10.1093/fampra/cmae063</a><br>
<a href="https://www.zotero.org/google-docs/?FqHu66">Healy, D., &amp; Mangin, D. (2024). Post-SSRI sexual dysfunction: Barriers to quantifying incidence and prevalence. <em>Epidemiology and Psychiatric Sciences</em>, <em>33</em>, e40. https://doi.org/10.1017/S2045796024000441</a><br>
<a href="https://www.zotero.org/google-docs/?FqHu66">Hengartner, M. P. (2021). <em>Evidence-biased antidepressant prescription: Overmedicalisation, flawed research, and conflicts of interest</em>. Springer.</a><br>
<a href="https://www.zotero.org/google-docs/?FqHu66">Hengartner, M. P., &amp; Plöderl, M. (2018). Statistically significant antidepressant-placebo differences on subjective symptom-rating scales do not prove that antidepressants work: Effect size and method bias matter! <em>Frontiers in Psychiatry</em>, <em>9</em>. https://doi.org/10.3389/fpsyt.2018.00517</a><br>
<a href="https://www.zotero.org/google-docs/?FqHu66">Hengartner, M. P., &amp; Plöderl, M. (2022). Estimates of the minimal important difference to evaluate the clinical significance of antidepressants in the acute treatment of moderate-to-severe depression. <em>BMJ Evidence-Based Medicine</em>, <em>27</em>(2), 69–73. https://doi.org/10.1136/bmjebm-2020-111600</a><br>
<a href="https://www.zotero.org/google-docs/?FqHu66">Hetrick, S. E., McKenzie, J. E., Bailey, A. P., Sharma, V., Moller, C. I., Badcock, P. B., Cox, G. R., Merry, S. N., &amp; Meader, N. (2021). New generation antidepressants for depression in children and adolescents: A network meta-analysis. <em>Cochrane Database of Systematic Reviews</em>, <em>2021</em>(5). https://doi.org/10.1002/14651858.CD013674.pub2</a><br>
<a href="https://www.zotero.org/google-docs/?FqHu66">Högberg, G. N., Antonuccio, D. O., &amp; Healy, D. (2015). Suicidal risk from TADS study was higher than it first appeared. <em>The International Journal of Risk &amp; Safety in Medicine</em>, <em>27</em>(2), 85–91. https://doi.org/10.3233/JRS-150645</a><br>
<a href="https://www.zotero.org/google-docs/?FqHu66">Le Noury, J., Nardo, J. M., Healy, D., Jureidini, J., Raven, M., Tufanaru, C., &amp; Abi-Jaoude, E. (2015). Restoring Study 329: Efficacy and harms of paroxetine and imipramine in treatment of major depression in adolescence. <em>BMJ</em>, h4320. https://doi.org/10.1136/bmj.h4320</a><br>
<a href="https://www.zotero.org/google-docs/?FqHu66">Naudet, F., Pellen, C., Fodor, L. A., Gastaldon, C., Barbui, C., Turner, E. H., Le Pabic, E., &amp; Cristea, I. A. (2025). Efficacy and safety of esketamine for “treatment resistant depression”: Registered report for a systematic review with an individual patient data meta-analysis of randomized, double-blind, placebo-controlled trials. <em>BMC Medicine</em>, <em>23</em>(1), 677. https://doi.org/10.1186/s12916-025-04435-x</a><br>
<a href="https://www.zotero.org/google-docs/?FqHu66">Pirani, Y., Delgado-Ron, J. A., Marinho, P., Gupta, A., Grey, E., Watt, S., MacKinnon, K. R., &amp; Salway, T. (2024). Frequency of self-reported persistent post-treatment genital hypoesthesia among past antidepressant users: A cross-sectional survey of sexual and gender minority youth in Canada and the US. <em>Social Psychiatry and Psychiatric Epidemiology</em>. https://doi.org/10.1007/s00127-024-02769-0</a><br>
<a href="https://www.zotero.org/google-docs/?FqHu66">Plöderl, M. (2025). <em>Concerning harm/benefit ratio of escitalopram for pediatric generalized anxiety disorder</em>. Open Science Framework. https://doi.org/10.31219/osf.io/tv823_v1</a><br>
<a href="https://www.zotero.org/google-docs/?FqHu66">Plöderl, M., Horowitz, M. A., &amp; Hengartner, M. P. (2023). Re: “A Multicenter Double-Blind, Placebo-Controlled Trial of Escitalopram in Children and Adolescents with Generalized Anxiety Disorder” by Strawn et al.—Concerning Harm–Benefit Ratio in a Recent Trial About Escitalopram for Generalized Anxiety Disorder. <em>Journal of Child and Adolescent Psychopharmacology</em>, <em>33</em>(7), 295–296. https://doi.org/10.1089/cap.2023.0029</a><br>
<a href="https://www.zotero.org/google-docs/?FqHu66">Plöderl, M., Horowitz, M., Naudet, F., Warren, J., &amp; Moncrieff, J. (2026). <em>Concerning harm/benefit ratio of escitalopram for pediatric generalized anxiety disorder. A critical viewpoint on the evidence and approval process</em>. PsyArXiv. https://doi.org/10.31234/osf.io/6fqk4_v1</a><br>
<a href="https://www.zotero.org/google-docs/?FqHu66">Plöderl, M., Lyus, R., Horowitz, M. A., &amp; Moncrieff, J. (2026). The loss of efficacy of fluoxetine in pediatric depression: Explanations, lack of acknowledgment, and implications for other treatments. <em>Journal of Clinical Epidemiology</em>, <em>189</em>, 112016. https://doi.org/10.1016/j.jclinepi.2025.112016</a><br>
<a href="https://www.zotero.org/google-docs/?FqHu66">Serretti, A., &amp; Chiesa, A. (2009). Treatment-Emergent Sexual Dysfunction Related to Antidepressants: A Meta-Analysis. <em>Journal of Clinical Psychopharmacology</em>, <em>29</em>(3), 259–266. https://doi.org/10.1097/JCP.0b013e3181a5233f</a><br>
<a href="https://www.zotero.org/google-docs/?FqHu66">Slee, A., Nazareth, I., Bondaronek, P., Liu, Y., Cheng, Z., &amp; Freemantle, N. (2019). Pharmacological treatments for generalised anxiety disorder: A systematic review and network meta-analysis. <em>The Lancet</em>, <em>393</em>(10173), 768–777. https://doi.org/10.1016/S0140-6736(18)31793-8</a><br>
<a href="https://www.zotero.org/google-docs/?FqHu66">Stone, M. B., Laughren, T. P., Jones, M. L., Levenson, M., Holland, P. C., Hughes, A., Hammad, T. A., Temple, R., &amp; Rochester, G. (2009). Risk of suicidality in clinical trials of antidepressants in adults: Analysis of proprietary data submitted to US Food and Drug Administration. <em>BMJ</em>, <em>339</em>, 1–10.</a><br>
<a href="https://www.zotero.org/google-docs/?FqHu66">Strawn, J. R., &amp; Mills, J. A. (2024). Response to Plöderl et al.&nbsp;re: “A Multicenter Double-Blind, Placebo-Controlled Trial of Escitalopram in Children and Adolescents with Generalized Anxiety Disorder.” <em>Journal of Child and Adolescent Psychopharmacology</em>, <em>34</em>(2), 106–107. https://doi.org/10.1089/cap.2023.0089</a><br>
<a href="https://www.zotero.org/google-docs/?FqHu66">Strawn, J. R., Mills, J. A., Schroeder, H., Mossman, S. A., Varney, S. T., Ramsey, L. B., Poweleit, E. A., Desta, Z., Cecil, K., &amp; DelBello, M. P. (2020). Escitalopram in Adolescents With Generalized Anxiety Disorder: A Double-Blind, Randomized, Placebo-Controlled Study. <em>The Journal of Clinical Psychiatry</em>, <em>81</em>(5). https://doi.org/10.4088/JCP.20m13396</a><br>
<a href="https://www.zotero.org/google-docs/?FqHu66">Strawn, J. R., Moldauer, L., Hahn, R. D., Wise, A., Bertzos, K., Eisenberg, B., Greenberg, E., Liu, C., Gopalkrishnan, M., McVoy, M., &amp; Knutson, J. A. (2023). A Multicenter Double-Blind, Placebo-Controlled Trial of Escitalopram in Children and Adolescents with Generalized Anxiety Disorder. <em>Journal of Child and Adolescent Psychopharmacology</em>, <em>33</em>(3), 91–100. https://doi.org/10.1089/cap.2023.0004</a><br>
<a href="https://www.zotero.org/google-docs/?FqHu66">Strawn, J. R., &amp; Walkup, J. T. (2025). Fact Versus Fear: Antidepressants in Children and Adolescents. <em>Journal of Clinical Psychopharmacology</em>, <em>45</em>(5), 413–417. https://doi.org/10.1097/JCP.0000000000002054</a></p>




<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>The MCID is derived from within-group comparisons and there is discussion about whether it is feasible to apply the MCID to between-group comparisons. A different approach would be to use the “smallest worthwhile effect” (SWE) where patients are asked what benefit they expect in light of the costs/harms of a treatment. This approach has not been utilized for pediatric psychiatric trials. For adult antidepressant trials, the first study shows that the median SWE corresponds with an at least 20% higher chance to achieve response compared to no treatment. Antidepressants only have about a 15% superiority to no treatment and about 12% to placebo. In the case of escitalopram I discuss here, the drug-placebo difference in response is only about 6%. This is very unlikely to exceed the SWE, especially in light of the harms discussed below.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>